spring:
  application:
    name: header backend application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homedatabase
    username: root
    password: Ankit@1992
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ankitdungarwal92@gmail.com
    password: elqp sqco wiwo gsqi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080




gmail:
  username: "ankitdungarwal92@gmail.com"
  #password: "bqzx utpx doyr gvns"
  password: "elqp sqco wiwo gsqi"